# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/bus.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'protos/bus.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10protos/bus.proto\x12\x03\x62us\"2\n\nBusPayload\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\x14\n\x0cpayload_json\x18\x02 \x01(\t\"7\n\x0b\x42usResponse\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\x12\x13\n\x0bresult_json\x18\x02 \x01(\t2B\n\nBusService\x12\x34\n\x0f\x44ispatchRequest\x12\x0f.bus.BusPayload\x1a\x10.bus.BusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.bus_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BUSPAYLOAD']._serialized_start=25
  _globals['_BUSPAYLOAD']._serialized_end=75
  _globals['_BUSRESPONSE']._serialized_start=77
  _globals['_BUSRESPONSE']._serialized_end=132
  _globals['_BUSSERVICE']._serialized_start=134
  _globals['_BUSSERVICE']._serialized_end=200
# @@protoc_insertion_point(module_scope)
