# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/bus.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'protos/bus.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10protos/bus.proto\x12\x03\x62us\"I\n\nBusRequest\x12\x16\n\x0etarget_service\x18\x01 \x01(\t\x12\x12\n\nevent_name\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\t\"A\n\x0b\x42usResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x10\n\x08metadata\x18\x03 \x01(\t2<\n\tBusRouter\x12/\n\nRouteEvent\x12\x0f.bus.BusRequest\x1a\x10.bus.BusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.bus_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BUSREQUEST']._serialized_start=25
  _globals['_BUSREQUEST']._serialized_end=98
  _globals['_BUSRESPONSE']._serialized_start=100
  _globals['_BUSRESPONSE']._serialized_end=165
  _globals['_BUSROUTER']._serialized_start=167
  _globals['_BUSROUTER']._serialized_end=227
# @@protoc_insertion_point(module_scope)
